   # Имя рабочей процедуры
   name: CI/CD Workflow

   # Запускаем workflow при любом пушинге в ветку main/master
   on:
     push:
       branches:
         - main
         - master

   # Основной Job, определяющий этапы выполнения
   jobs:
     build:
       runs-on: ubuntu-latest

       steps:
         - name: Check out the repository
           uses: actions/checkout@v2

         - name: Install dependencies
           run: npm install

         - name: Run tests
           run: npm test
   
